### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: gnu/io/CommPortIdentifier

### ISSUE THREAD

**Issue by aj22r** [mkeller0815/MEEPROMMER#8]
I have RXTXcomm.jar in C:\Program Files (x86)\Java\jdk1.8.0_131\jre\lib\ext and rxtxSerial.dll in C:\Program Files (x86)\Java\jdk1.8.0_131\jre\bin but it still gives me the error

**Comment by mkeller0815** [comment]
Please follow the installation instructions in http://rxtx.qbang.org/wiki/index.php/Installation_for_Windows
Also check that the SimpleJBurn is executed by the java version you have the rxtx lib installed for. 
Hope that helps.

**Comment by leomil72** [comment]
I have librxtx installed in my system but get the same error. Ah, I'm using Linux:

`Exception in thread "main" java.lang.NoClassDefFoundError: gnu/io/CommPortIdentifier
	at SimpleJBurn.MySerial.getAvailableSerialPorts(MySerial.java:36)
	at SimpleJBurn.MainFrame.initComponents(MainFrame.java:329)
	at SimpleJBurn.MainFrame.<init>(MainFrame.java:270)
	at SimpleJBurn.SimpleJBurn.main(SimpleJBurn.java:17)
Caused by: java.lang.ClassNotFoundException: gnu.io.CommPortIdentifier
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 4 more
`
